# NumPy

In [1]:
import numpy as np

# Creating Arrays

In [4]:
a = np.array([1,2,3])
b = np.array([(1.5,2,3), (4,5,6)], dtype = float)
c = np.array([[(1.5,2,3), (4,5,6)],[(3,2,1), (4,5,6)]], dtype = float)

In [5]:
a

array([1, 2, 3])

In [6]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [7]:
c

array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 1. ],
        [4. , 5. , 6. ]]])

# Initial Placeholders

In [8]:
#Create an array of zeros
np.zeros((3,4))  

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
#Create an array of ones
np.ones((2,3,4),dtype=np.int16) 

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [12]:
#Create an array of evenly spaced Values (step value)
d = np.arange(10,25,5) 
d

array([10, 15, 20])

In [13]:
#Create an array of evenlyspaced values (number of samples)
np.linspace(0,2,9) 

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [14]:
#Create a constant array
e = np.full((2,2),7)
e

array([[7, 7],
       [7, 7]])

In [15]:
#Create a 2x2 identity matrix
f = np.eye(2)
f

array([[1., 0.],
       [0., 1.]])

In [16]:
#Create an array with random values
np.random.random((2,2))

array([[0.2627897 , 0.00546132],
       [0.11995333, 0.02233721]])